# Generated by Django 4.0.6 on 2022-07-28 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Booking-Status',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Payment-Status',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Seat-Type',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('seats', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('booking_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.bookingstatus')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
