# Generated by Django 4.0.6 on 2022-08-02 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'], unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Payment Modes',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['seat_type'], unique=True)),
            ],
            options={
                'verbose_name_plural': 'Seat-Type',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['movie__slug'], unique=True)),
                ('cinema_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahall')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('transaction_id', models.CharField(max_length=20)),
                ('payment_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.coupen')),
                ('payment_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentstatus')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentmode')),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_message', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('notification_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie')),
                ('notification_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.notificationtype')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='CinemaHallSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatRow', models.CharField(max_length=100)),
                ('seatColumn', models.CharField(max_length=100)),
                ('seat_number', models.IntegerField()),
                ('cinema_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahall')),
                ('seat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.seattype')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True)),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('seats', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('booking_status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.bookingstatus')),
                ('cinema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinema')),
                ('cinemahall', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahall')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie')),
                ('payment_status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentstatus')),
                ('show', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.show')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('date', 'start_time', 'end_time', 'movie', 'cinema_hall'), name='unique show'),
        ),
    ]
