# Generated by Django 4.0.6 on 2022-08-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0002_coupen_movie_notificationtype_paymentmode_seattype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='show',
        ),
        migrations.AddField(
            model_name='show',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinema'),
        ),
    ]
