# Generated by Django 4.0.6 on 2022-08-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0002_cinemahallseat_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahallseat',
            name='booking_status',
            field=models.ForeignKey(default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.bookingstatus'),
        ),
    ]
