# Generated by Django 4.0.6 on 2022-08-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0002_remove_cinemahallseat_show_timing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahallseat',
            name='show',
        ),
        migrations.AddField(
            model_name='show',
            name='cinemahallseat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahallseat'),
        ),
        migrations.AddField(
            model_name='show',
            name='timing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ShowTiming',
        ),
    ]
