# Generated by Django 4.0.6 on 2022-08-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0003_alter_cinemahallseat_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cinemahallseat',
            name='booking_status',
        ),
        migrations.AddField(
            model_name='cinemahallseat',
            name='state',
            field=models.ForeignKey(default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.seatstate'),
        ),
    ]
