# Generated by Django 4.0.6 on 2022-07-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0003_alter_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.accountstatus'),
        ),
    ]
