# Generated by Django 4.0.6 on 2022-08-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0003_remove_cinemahallseat_show_show_cinemahallseat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='cinemahallseat',
        ),
        migrations.RemoveField(
            model_name='show',
            name='timing',
        ),
        migrations.CreateModel(
            name='ShowWiseSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_hall_seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahallseat')),
                ('show', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.show')),
            ],
        ),
    ]
