# Generated by Django 4.0.6 on 2022-08-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0003_remove_cinema_show_show_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinema'),
        ),
    ]
