# Generated by Django 4.0.6 on 2022-07-28 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0004_alter_user_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('movie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='cinema',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, to='Movie_booking_app.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.bookingstatus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cinema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinema'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.accountstatus'),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinema')),
                ('cinema_hall', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahall')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaHallSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatRow', models.CharField(max_length=100)),
                ('seatColumn', models.CharField(max_length=100)),
                ('seat_number', models.IntegerField()),
                ('cinema_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahall')),
                ('seat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.seattype')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cinemahall',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahall'),
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.show'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahall'),
        ),
    ]
