# Generated by Django 4.0.6 on 2022-08-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0004_seatstate_remove_cinemahallseat_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='price',
        ),
        migrations.AddField(
            model_name='show',
            name='available_seats',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='total_seats',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='cinemahallseat',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.seatstate'),
        ),
    ]
