# Generated by Django 4.0.6 on 2022-08-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0004_remove_show_cinemahallseat_remove_show_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showwiseseats',
            name='state',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.seatstate'),
        ),
    ]
