# Generated by Django 4.0.6 on 2022-08-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0005_cinemahall_unique cinemahallname'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='show',
            name='unique show',
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('date', 'start_time', 'end_time', 'movie', 'cinema_hall', 'cinema'), name='unique show'),
        ),
    ]
