# Generated by Django 4.0.6 on 2022-08-03 11:31

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0005_remove_show_price_show_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahallseat',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['cinema_hall__slug'], unique=True),
        ),
    ]
