# Generated by Django 4.0.6 on 2022-08-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0005_showwiseseats_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showwiseseats',
            unique_together={('show', 'cinema_hall_seat', 'state')},
        ),
    ]
