# Generated by Django 4.0.6 on 2022-07-28 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0005_cinemahall_alter_user_options_cinema_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Payment Modes',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('transaction_id', models.CharField(max_length=20)),
                ('payment_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentstatus')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentmode')),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
