# Generated by Django 4.0.6 on 2022-08-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0006_remove_show_unique show_show_unique show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
