# Generated by Django 4.0.6 on 2022-08-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0006_cinemahallseat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentmode'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahallseat'),
        ),
    ]
