# Generated by Django 4.0.6 on 2022-07-29 08:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0007_coupen_notificationtype_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='username'),
        ),
    ]
