# Generated by Django 4.0.6 on 2022-08-04 04:53

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0007_remove_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_booked',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['user__name'], unique=True),
        ),
    ]
