# Generated by Django 4.0.6 on 2022-08-04 04:54

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0008_booking_date_booked_booking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['user__username'], unique=True),
        ),
    ]
