# Generated by Django 4.0.6 on 2022-07-29 08:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0008_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='seattype',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, null=True, populate_from='seat_type', unique=True),
        ),
        migrations.AddField(
            model_name='show',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, null=True, populate_from='movie_name', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, null=True, populate_from='username', unique=True),
        ),
    ]
