# Generated by Django 4.0.6 on 2022-08-01 12:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0009_cinema_slug_cinemahall_slug_movie_slug_seattype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='username', unique=True),
        ),
    ]
