# Generated by Django 4.0.6 on 2022-08-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0009_alter_booking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
