# Generated by Django 4.0.6 on 2022-08-01 12:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0010_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=['first_name', 'last-name']),
        ),
    ]
