# Generated by Django 4.0.6 on 2022-08-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0011_alter_booking_date_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_booked',
        ),
    ]
