# Generated by Django 4.0.6 on 2022-08-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0014_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahallseat',
            name='price',
            field=models.IntegerField(default=150, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.bookingstatus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.paymentstatus'),
        ),
    ]
