# Generated by Django 4.0.6 on 2022-08-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0015_cinemahallseat_price_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(blank=True, to='Movie_booking_app.cinemahallseat'),
        ),
    ]
