# Generated by Django 4.0.6 on 2022-08-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0016_remove_booking_seats_booking_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinema'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cinemahall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.cinemahall'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_booking_app.show'),
        ),
    ]
