# Generated by Django 4.0.6 on 2022-08-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_booking_app', '0018_alter_booking_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
